### ISSUE TITLE
No text being translated 

### ISSUE THREAD

**Issue by fznx922** [killkimno/MORT#21] opened 2023-12-23 04:10 UTC
Hey there! love this app, actually it used to work fine, after updating windows and coming back to it, seems it doesnt work now, ive set it up many different ways, but no results are showing, regardless of if i use overlay or text box etc, when choosing window i can see that the console is doing something but my NLLB api isnt recieving any requests, ive tried with deep l and google but both doing nothing

when trying to do image adjustment, i do noticed it pops up with an error, im not sure if this applies to it but maybe it does 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height)
   at MORT.OcrAreaForm.ShowColorPicker(Boolean isShowResult, Boolean isUseRgb, Boolean isUseHSv, Boolean isUseThreshold, ColorGroup colorGroup, Int32 threshold) in D:\project\MORT\64bit\MORT\MORT\OcrAreaForm.cs:line 478
   at MORT.FormManager.ShowColorPickResult(Boolean isUseRgb, Boolean isUseHSv, Boolean isUseThreshold, ColorGroup colorGroup, Int32 threshold) in D:\project\MORT\64bit\MORT\MORT\Manager\FormManager.cs:line 478
   at MORT.Form1.OnClickShowImgResult(Object sender, EventArgs e) in D:\project\MORT\64bit\MORT\MORT\Form1Button.cs:line 70
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.222.60605
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.2/System.Private.CoreLib.dll

**Comment by killkimno** [comment] 2023-12-23 08:39
hello! The cause of the problem has been determined.
This problem occurred because the OCR area was not set properly.

Try -> Search Button Click -> Default Click or MORT -> Additional Tab -> Reset Config then try again

**Comment by killkimno** [comment] 2023-12-24 08:16
hello!
The above issue has been resolved in the latest version
https://github.com/killkimno/MORT/releases/tag/1.270

**Closed by killkimno** 2023-12-24 08:16 UTC
